In [1]:
import pandas as pd
import numpy as np
import os
import sys
from pathlib import Path
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
root_path = Path(os.getcwd()).resolve().parent

In [3]:
sys.path.append(str(root_path))

In [4]:
from src.utils.auto_importer import AutoImporter, DataFrameDescriber, CompleteDescribeTable, BoxplotVisualizer

In [5]:
pd.set_option('display.max_columns',500)
# pd.set_option('display.max_rows',500)

In [6]:
df = pd.read_csv("../data/raw/heart_attack_prediction_dataset1.csv")

In [7]:
data = df.copy()

In [8]:
data

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,59,M,ASY,156,96,0,LVH,177,Y,1.6,Flat,1
1,57,M,ASY,135,413,0,Normal,125,Y,-0.1,Up,1
2,58,M,ATA,130,410,0,Normal,124,N,1.2,Up,1
3,65,M,ASY,134,149,0,ST,190,N,1.0,Flat,1
4,57,F,ATA,125,156,0,Normal,140,Y,-0.1,Flat,0
...,...,...,...,...,...,...,...,...,...,...,...,...
18558,53,M,ASY,161,8,0,Normal,100,Y,2.0,Up,0
18559,56,M,ASY,127,60,0,Normal,124,N,-0.1,Flat,0
18560,55,M,ASY,144,517,0,Normal,112,Y,-0.1,Up,1
18561,60,M,ASY,130,253,0,Normal,144,Y,0.1,Up,1
18562,50,F,NAP,127,225,0,LVH,120,N,-1.0,Flat,1

In [9]:
primera_inspeccion = AutoImporter(data)
descripcion_data = DataFrameDescriber(data)
tabla_completa = CompleteDescribeTable(data)

In [10]:
primera_inspeccion.inspeccion_inicial()

=== TAMAÃ‘O Y ESTRUCTURA DE LOS DATOS ===
NÃºmero total de registros: 18563
NÃºmero de columnas: 12
Uso de memoria: 1740.41 KB


=== TIPOS DE DATOS Y NOMBRES DE COLUMNAS ===
Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object


InformaciÃ³n detallada del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18563 entries, 0 to 18562
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             18563 non-null  int64
 1   Sex             18563 non-null  object
 2   ChestPainType   18563 non-null  object
 3   RestingBP       18563 non-null  int64
 4   Cholesterol     18563 non-null  int64
 5   FastingBS       18563 non-null  int64
 6   RestingECG      18563 non-null  object
 7   MaxHR           18563 non-null  int64
 8   ExerciseAngina  18563 non-null  object
 9   Oldpeak         18563 non-null  float64
 10  ST_Slope        18563 non-null  object
 11  HeartDisease    18563 non-null  int64
dtypes: float64(1), int64(6), object(5)
memory usage: 1.7+ MB
None


=== IDENTIFICACIÃ“N DE PROBLEMAS INICIALES ===
NÃºmero de filas duplicadas: 0

Valores nulos por columna:
Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

Valores nulos relativos por columna:
Age               0.0
Sex               0.0
ChestPainType     0.0
RestingBP         0.0
Cholesterol       0.0
FastingBS         0.0
RestingECG        0.0
MaxHR             0.0
ExerciseAngina    0.0
Oldpeak           0.0
ST_Slope          0.0
HeartDisease      0.0
dtype: float64 2

Primeras filas del dataset:
   Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   59   M           ASY        156           96          0        LVH    177
1   57   M           ASY        135          413          0     Normal    125
2   58   M           ATA        130          410          0     Normal    124
3   65   M           ASY        134          149          0         ST    190
4   57   F           ATA        125          156          0     Normal    140

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease
0              Y      1.6     Flat             1
1              Y     -0.1       Up             1
2              N      1.2       Up             1
3              N      1.0     Flat             1
4              Y     -0.1     Flat             0

In [11]:
descripcion_data.describe_numerico()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,18563.000000,18563.000000,18563.000000,18563.000000,18563.000000,18563.000000,18563.000000
mean,56.207779,132.008242,200.264936,0.043905,136.585196,0.649017,0.539783
std,8.793356,18.465068,106.087365,0.204888,25.387793,0.999013,0.498428
min,28.000000,0.000000,0.000000,0.000000,60.000000,-1.600000,0.000000
25%,50.000000,120.000000,126.000000,0.000000,119.000000,-0.100000,0.000000
50%,56.000000,132.000000,201.000000,0.000000,137.000000,0.200000,1.000000
75%,62.000000,144.000000,271.000000,0.000000,154.000000,1.300000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,5.700000,1.000000

In [12]:
descripcion_data.describe_categorico()

          Sex ChestPainType RestingECG ExerciseAngina ST_Slope
count   18563         18563      18563          18563    18563
unique      2             4          3              2        3
top         M           ASY     Normal              N     Flat
freq    14632         10027      11170          11099     9302

In [13]:
tabla_completa.describe_complete()

c:\Users\Felipe\Desktop\THE-BRIDGE\THEBRIDGE-BOOTCAMP\PROYECTO_ML_HEART_DISEASE\.venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:586: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 18563.
  res = hypotest_fun_out(*samples, **kwds)
c:\Users\Felipe\Desktop\THE-BRIDGE\THEBRIDGE-BOOTCAMP\PROYECTO_ML_HEART_DISEASE\.venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:586: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 18563.
  res = hypotest_fun_out(*samples, **kwds)
c:\Users\Felipe\Desktop\THE-BRIDGE\THEBRIDGE-BOOTCAMP\PROYECTO_ML_HEART_DISEASE\.venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:586: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 18563.
  res = hypotest_fun_out(*samples, **kwds)
c:\Users\Felipe\Desktop\THE-BRIDGE\THEBRIDGE-BOOTCAMP\PROYECTO_ML_HEART_DISEASE\.venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:586: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 18563.
  res = hypotest_fun_out(*samples, **kwds)
c:\Users\Felipe\Desktop\THE-BRIDGE\THEBRIDGE-BOOTCAMP\PROYECTO_ML_HEART_DISEASE\.venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:586: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 18563.
  res = hypotest_fun_out(*samples, **kwds)
c:\Users\Felipe\Desktop\THE-BRIDGE\THEBRIDGE-BOOTCAMP\PROYECTO_ML_HEART_DISEASE\.venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:586: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 18563.
  res = hypotest_fun_out(*samples, **kwds)
c:\Users\Felipe\Desktop\THE-BRIDGE\THEBRIDGE-BOOTCAMP\PROYECTO_ML_HEART_DISEASE\.venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:586: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 18563.
  res = hypotest_fun_out(*samples, **kwds)

In [14]:
tabla_completa.get_describe_complete()

,tipo de dato,tipo de variable,cardinalidad abs,cardinalidad %,distribucion,% missing,% Outliers,rango,moda,mediana,media,desv estandar,Q1,Q3,asimetria,curtosis,Valor estad.,Valor de P,prueba normalidad,tipo asimetria
variable,,,,,,,,,,,,,,,,,,,,
Age,int64,numerica,50,0.269353,No Gaussiana,0.0,0.30,"(28, 77)",56.0,56.0,56.207779,8.793356,50.0,62.0,-0.059695,-0.132470,0.996810,1.903367e-19,No normal,negativa
Sex,object,categorica,2,0.010774,None,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
ChestPainType,object,categorica,4,0.021548,None,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
RestingBP,int64,numerica,135,0.727253,No Gaussiana,0.0,0.94,"(0, 200)",140.0,132.0,132.008242,18.465068,120.0,144.0,0.001415,0.139107,0.999159,5.226785e-08,No normal,negativa
Cholesterol,int64,numerica,535,2.882077,No Gaussiana,0.0,0.45,"(0, 603)",0.0,201.0,200.264936,106.087365,126.0,271.0,0.140896,-0.260938,0.990677,9.732569e-33,No normal,negativa
FastingBS,int64,numerica,2,0.010774,No Gaussiana,0.0,4.39,"(0, 1)",0.0,0.0,0.043905,0.204888,0.0,0.0,4.452619,17.827733,0.205686,5.436700e-127,No normal,negativa
RestingECG,object,categorica,3,0.016161,None,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
MaxHR,int64,numerica,143,0.770350,No Gaussiana,0.0,0.29,"(60, 202)",140.0,137.0,136.585196,25.387793,119.0,154.0,-0.042732,-0.147237,0.998646,1.879081e-11,No normal,negativa
ExerciseAngina,object,categorica,2,0.010774,None,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
Oldpeak,float64,numerica,70,0.377094,No Gaussiana,0.0,1.30,"(-1.6, 5.7)",-0.0,0.2,0.649017,0.999013,-0.1,1.3,0.951320,0.676901,0.922576,9.714513e-70,No normal,positiva
ST_Slope,object,categorica,3,0.016161,None,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
HeartDisease,int64,numerica,2,0.010774,No Gaussiana,0.0,0.00,"(0, 1)",1.0,1.0,0.539783,0.498428,0.0,1.0,-0.159653,-1.974724,0.634320,5.490231e-106,No normal,negativa

------------------------------------------

Limpieza de los datos

Cambio de nombre de las columnas para castellano

In [15]:
new_column_names = {
    'Age': 'Edad',
    'Sex': 'Sexo',
    'ChestPainType': 'TipoDolorTorax',
    'RestingBP': 'PresionArterialReposo',
    'Cholesterol': 'Colesterol',
    'FastingBS': 'GlucosaEnAyunas',
    'RestingECG': 'ECGReposo',
    'MaxHR': 'FreqCardiacaMaxima',
    'ExerciseAngina': 'AnginaDeEsfuerzo',
    'Oldpeak': 'DescensoST',
    'ST_Slope': 'PendienteST',
    'HeartDisease': 'EnfermedadCardiaca'
}

In [16]:
data.rename(columns=new_column_names, inplace=True)

se nota la presencia de valores min = 0 en las columnas Cholesterol y FastingBS, esto no puede pasar, por esto vamos a ver cuantos son estes datos y lo que podemos hacer con ellos

In [17]:
data[data['PresionArterialReposo'] == 0]

,Edad,Sexo,TipoDolorTorax,PresionArterialReposo,Colesterol,GlucosaEnAyunas,ECGReposo,FreqCardiacaMaxima,AnginaDeEsfuerzo,DescensoST,PendienteST,EnfermedadCardiaca
2189,55,M,NAP,0,0,0,Normal,155,N,-0.9,Flat,1

en el caso de la columna RestingBP vamos a quitar dicho registro, pues no causa perdida en la analise de todo el conjunto de datos, devido a cuantidad sin relevancia

In [18]:
data = data.loc[data['PresionArterialReposo'] != 0]

Vamos hacer la misma comprobacion en la columna Cholesterol

In [19]:
data['Colesterol'].value_counts()

Colesterol
0      776
254     81
224     81
210     80
182     78
      ...
462      1
510      1
481      1
506      1
540      1
Name: count, Length: 535, dtype: int64

Como son muchos valores, para esta columna no se puede borrar tales datos, vamos substituir los valores 0 de esta columna por el valor de la media de los valores de la columna. Para calcular la media de esta columna, vamos calcular sin utilizar los valores que actualmente estan iguales a 0 para no sesgar los datos calculados.

In [20]:
data['Colesterol'].replace(0, np.nan, inplace=True);

C:\Users\Felipe\AppData\Local\Temp\ipykernel_21608\2433983230.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Colesterol'].replace(0, np.nan, inplace=True);
C:\Users\Felipe\AppData\Local\Temp\ipykernel_21608\2433983230.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Colesterol'].replace(0, np.nan, inplace=True);

In [21]:
data['Colesterol'].fillna(data['Colesterol'].mean(), inplace=True);

C:\Users\Felipe\AppData\Local\Temp\ipykernel_21608\3643165781.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Colesterol'].fillna(data['Colesterol'].mean(), inplace=True);

----------------------------------------

Guardar archivo procesado tras los tratamientos realizados en los datos

In [22]:
data.to_csv("../data/processed/heart_attack_prediction_dataset1_processed.csv", index=False)

-----------------------------------